use_frameworks!

target 'GTFSStationsParis_Example' do
  pod 'GTFSStationsParis', :path => '../'
  pod 'SubwayStations', git: 'https://github.com/schrockblock/subway-stations'
  pod 'SQLite.swift', '~> 0.11.0'

  target 'GTFSStationsParis_Tests' do
    inherit! :search_paths
    
    pod 'GTFSStationsParis', :path => '../'
    pod 'SubwayStations', git: 'https://github.com/schrockblock/subway-stations'
    pod 'Quick'
    pod 'Nimble'
  end
end
