source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GTFSStationsParis_Example' do
  pod 'GTFSStationsParis', :path => '../'

  target 'GTFSStationsParis_Tests' do
    inherit! :search_paths
    
    pod 'GTFSStationsParis', :path => '../'
    pod 'Quick'
    pod 'Nimble'
  end
end
